DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Controllers/ButtonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using Tracy.Frameworks.Common.Extends;
using Tracy.WebFrameworks.IService;

namespace Tracy.WebFrameworks.Offline.Site.Controllers
{
    public class ButtonController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// 获取当前用户当前页面可访问的按钮
        /// </summary>
        /// <param name="menuCode"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetButtonByUserIdAndMenuCode(string menuCode, string pageName)
        {
            if (menuCode.IsNullOrEmpty())
            {
                throw new ArgumentNullException("menuCode");
            }

            var result = string.Empty;
            using (var factory = new ChannelFactory<IWebFxsButtonService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.GetButtonByUserIdAndMenuCode(menuCode, pageName, CurrentUserInfo.Id);
                if (rs.ReturnCode == Entity.ReturnCodeType.Success)
                {
                    result = rs.Content;
                }
            }

            return Content(result);
        }

    }
}

DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Controllers/CorporationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using Tracy.WebFrameworks.Offline.Site.Filters;
using Tracy.WebFrameworks.IService;
using Tracy.WebFrameworks.Entity;
using Tracy.WebFrameworks.Entity.ViewModel;
using System.Text;
using Tracy.Frameworks.Common.Extends;
using Tracy.Frameworks.Common.Const;

namespace Tracy.WebFrameworks.Offline.Site.Controllers
{
    /// <summary>
    /// 公司管理
    /// </summary>
    public class CorporationController : BaseController
    {
        [LoginAuthorization]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        [LoginAuthorization]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(AddCorporationRQ request)
        {
            var flag = false;
            var msg = string.Empty;

            using (var factory = new ChannelFactory<IWebFxsCorporationService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.AddCorporation(request, base.CurrentUserInfo);
                if (rs.ReturnCode == ReturnCodeType.Success)
                {
                    flag = true;
                    msg = "添加成功!";
                }
                else
                {
                    msg = "添加失败!";
                }
            }

            return Json(new { success = flag, msg = msg }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 修改
        /// </summary>
        /// <returns></returns>
        [LoginAuthorization]
        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(EditCorporationRQ request)
        {
            var flag = false;
            var msg = string.Empty;

            using (var factory = new ChannelFactory<IWebFxsCorporationService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.EditCorporation(request, base.CurrentUserInfo);
                if (rs.ReturnCode == ReturnCodeType.Success)
                {
                    flag = true;
                    msg = "修改成功!";
                }
                else
                {
                    msg = "修改失败!";
                }
            }

            return Json(new { success = flag, msg = msg }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 删除公司
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(DeleteCorporationRQ request)
        {
            var flag = false;
            var msg = string.Empty;

            using (var factory = new ChannelFactory<IWebFxsCorporationService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.DeleteCorporation(request);
                if (rs.ReturnCode == ReturnCodeType.Success)
                {
                    flag = true;
                    msg = "删除成功!";
                }
                else
                {
                    msg = "删除失败!";
                }
            }

            return Json(new { success = flag, msg = msg }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 查询所有公司,并且以树形展示
        /// </summary>
        /// <returns></returns>
        public ActionResult GetAll()
        {
            var result = string.Empty;
            StringBuilder sb = new StringBuilder();
            using (var factory = new ChannelFactory<IWebFxsCorporationService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.GetAllCorps();
                if (rs.ReturnCode == Entity.ReturnCodeType.Success)
                {
                    var corps = rs.Content;
                    if (corps.HasValue())
                    {
                        sb.Append(RecursionCorp(corps, 0));
                        sb = sb.Remove(sb.Length - 2, 2);
                        result = sb.ToString();
                    }
                    else
                    {
                        result = "[]";
                    }
                }
            }

            return Content(result);
        }

        /// <summary>
        /// 递归所有公司
        /// </summary>
        /// <param name="list"></param>
        /// <param name="parentId"></param>
        /// <returns></returns>
        private string RecursionCorp(List<Corporation> list, int parentId)
        {
            StringBuilder sb = new StringBuilder();
            var childCorps = list.Where(p => p.ParentId == parentId).ToList();
            if (childCorps.HasValue())
            {
                sb.Append("[");
                for (int i = 0; i < childCorps.Count; i++)
                {
                    var childCorpStr = RecursionCorp(list, childCorps[i].Id);
                    if (!childCorpStr.IsNullOrEmpty())
                    {
                        sb.Append("{\"id\":\"" + childCorps[i].Id.ToString() + "\",\"ParentId\":\"" + childCorps[i].ParentId.ToString() + "\",\"Code\":\"" + childCorps[i].Code + "\",\"Enabled\":\"" + childCorps[i].Enabled.Value + "\",\"Sort\":\"" + childCorps[i].Sort.Value.ToString() + "\",\"CreatedTime\":\"" + childCorps[i].CreatedTime.Value.ToString(DateFormat.DATETIME) + "\",\"text\":\"" + childCorps[i].Name + "\",\"children\":");
                        sb.Append(childCorpStr);
                    }
                    else
                    {
                        sb.Append("{\"id\":\"" + childCorps[i].Id.ToString() + "\",\"ParentId\":\"" + childCorps[i].ParentId.ToString() + "\",\"Code\":\"" + childCorps[i].Code + "\",\"Enabled\":\"" + childCorps[i].Enabled.Value + "\",\"Sort\":\"" + childCorps[i].Sort.Value.ToString() + "\",\"CreatedTime\":\"" + childCorps[i].CreatedTime.Value.ToString(DateFormat.DATETIME) + "\",\"text\":\"" + childCorps[i].Name + "\"},");
                    }

                }
                sb.Remove(sb.Length - 1, 1);
                sb.Append("]},");
            }
            return sb.ToString();
        }

    }
}

DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Views/Corporation/Add.cshtml
<div style="padding: 15px; overflow: hidden">
    <form id="ui_corp_addform" method="post" action="">
        <table class="tableForm" width="100%">
            <tr>
                <th>
                    名称：
                </th>
                <td>
                    <input type="text" name="Name" id="Name"
                           class="easyui-validatebox" data-options="required:true" autocomplete="off" />
                </td>
            </tr>
            <tr>
                <th>
                    编码：
                </th>
                <td>
                    <input type="text" name="Code" id="Code"
                           class="easyui-validatebox" data-options="required:true" autocomplete="off" />
                </td>
            </tr>
            <tr>
                <th>
                    排序：
                </th>
                <td>
                    <input name="Sort" class="easyui-numberspinner" style="width: 70px;"
                           value="10" data-options="min:1,max:100,editable:false">
                </td>
            </tr>
            <tr>
                <th>
                    父节点：
                </th>
                <td>
                    <input class="easyui-combotree" id="ParentId" name="ParentId"
                           data-options="url: '@Url.Action("GetAll", "Corporation")',lines:true" />
                    <img style="cursor: pointer; vertical-align: middle;" onclick="$('#ParentId').combotree('clear');"
                         alt="清空父节点" title="清空父节点" src='@Url.Content("~/Content/easyui/icon/edit-clear.png")' />
                </td>
            </tr>
        </table>
    </form>
</div>

DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Views/Corporation/Edit.cshtml
<div style="padding: 15px; overflow: hidden">
    <form id="ui_corp_editform" method="post" action="">
        <table class="tableForm" width="100%">
            <tr>
                <th>
                    名称：
                </th>
                <td>
                    <input type="hidden" name="id" id="id" />
                    <input type="text" name="Name" id="Name"
                           class="easyui-validatebox" data-options="required:true" autocomplete="off" />
                </td>
            </tr>
            <tr>
                <th>
                    排序：
                </th>
                <td>
                    <input id="Sort" name="Sort" class="easyui-numberspinner"
                           style="width: 70px;" data-options="min:1,max:100,editable:false">
                </td>
            </tr>
        </table>
    </form>
</div>

DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Views/Corporation/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link type="image/x-icon" rel="shortcut icon" href="~/Content/images/favicon.ico" />
    @Styles.Render("~/Content/easyui/bootstrap")
    @Styles.Render("~/Content/site")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/easyui")
    @Scripts.Render("~/bundles/common")
    <title>公司管理</title>
</head>
<body>
    <div id="ui_corp_layout" class="easyui-layout" data-options="fit:true,border:false">
        <div data-options="region:'center',border:false">
            <table id="ui_corp_tg" data-options="fit:true,border:false"></table>
        </div>
    </div>

    @if (false)
    {
        <script type="text/javascript" src="~/Scripts/jquery-1.8.2.js"></script>
    }

    <script type="text/javascript">
        $(function () {
            //加载所有公司数据
            $.ajax({
                url: '@Url.Action("GetButtonByUserIdAndMenuCode", "Button")',
                type: "POST",
                dataType: "json",
                data: { "menuCode": "corp", "pageName": "corporation" },
                timeout: 5000,
                success: function (data) {
                    if (data.success) {
                        var oldSelectCorpId;
                        var toolbar = getToolBar(data);
                        if (data.browser) {
                            $("#ui_corp_tg").treegrid({
                                url: '@Url.Action("GetAll", "Corporation")',
                                idField: 'id',
                                treeField: 'text',
                                rownumbers: true,
                                columns: [[
                                            { field: 'text', title: '公司名称', width: 150 },
                                            { field: 'Code', title: '编码', width: 80 },
                                            {
                                                field: 'Enabled', title: '启用', sortable: true, width: 60, align: 'center',
                                                formatter: function (value, row, index) {
                                                    return value ? '<img src="@Url.Content("~/Content/easyui/icon/chk_checked.gif")" alt="已启用" title="公司已启用" />' : '<img src="@Url.Content("~/Content/easyui/icon/chk_unchecked.gif")" alt="未启用" title="公司未启用" />';
                                                }
                                            },
                                            { field: 'Sort', title: '排序', width: 60 },
                                            { field: 'CreatedTime', title: '创建时间', width: 150 }
                                ]],
                                toolbar: toolbar.length == 0 ? null : toolbar
                            });
                        }
                        else {
                            $.show_warning("提示", "无权限，请联系管理员！");
                        }
                    } else {
                        $.show_warning("错误", data.result);
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    if (textStatus == "timeout") {
                        $.show_warning("提示", "请求超时，请刷新当前页重试！");
                    }
                    else {
                        $.show_warning("错误", textStatus + "：" + errorThrown);
                    }
                }
            })
        });

        var corpIds = "";
        function recursionGetIds(rows) {
            if (rows.children != undefined) {
                $.each(rows.children, function (i, row) {
                    corpIds += row.id + ",";
                    recursionGetIds(row);
                });
            }
        };

        //添加公司
        function corporation_add() {
            $("<div/>").dialog({
                id: "ui_corp_add_dialog",
                href: '@Url.Action("Add", "Corporation")',
                title: "添加公司",
                height: 350,
                width: 460,
                modal: true,
                buttons: [{
                    id: "ui_corp_add_btn",
                    text: '添 加',
                    handler: function () {
                        $("#ui_corp_addform").form("submit", {
                            url: '@Url.Action("Add", "Corporation")',
                            onSubmit: function (param) {
                                $('#ui_corp_add_btn').linkbutton('disable');
                                if ($(this).form('validate'))
                                    return true;
                                else {
                                    $('#ui_corp_add_btn').linkbutton('enable');
                                    return false;
                                }
                            },
                            success: function (data) {
                                var dataJson = eval('(' + data + ')');
                                if (dataJson.success) {
                                    $("#ui_corp_add_dialog").dialog('destroy');
                                    $.show_warning("提示", dataJson.msg);
                                    $("#ui_corp_tg").treegrid("reload");
                                } else {
                                    $('#ui_corp_add_btn').linkbutton('enable');
                                    $.show_warning("提示", dataJson.msg);
                                }
                            }
                        });
                    }
                }],
                onLoad: function () {
                    $("#Name").focus();
                },
                onClose: function () {
                    $("#ui_corp_add_dialog").dialog('destroy');
                }
            });
        }

        //修改公司
        function corporation_edit() {
            var row = $("#ui_corp_tg").treegrid("getSelected");
            if (!row) {
                $.show_warning("提示", "请先选择要修改的公司");
                return;
            }
            $("<div/>").dialog({
                id: "ui_corp_edit_dialog",
                href: '@Url.Action("Edit", "Corporation")',
                title: "修改公司",
                height: 350,
                width: 460,
                modal: true,
                buttons: [{
                    id: "ui_corp_edit_btn",
                    text: '修 改',
                    handler: function () {
                        $("#ui_corp_editform").form("submit", {
                            url: '@Url.Action("Edit", "Corporation")',
                            onSubmit: function (param) {
                                $('#ui_corp_edit_btn').linkbutton('disable');
                                if ($(this).form('validate'))
                                    return true;
                                else {
                                    $('#ui_corp_edit_btn').linkbutton('enable');
                                    return false;
                                }
                            },
                            success: function (data) {
                                var dataJson = eval('(' + data + ')');
                                if (dataJson.success) {
                                    $("#ui_corp_edit_dialog").dialog('destroy');
                                    $.show_warning("提示", dataJson.msg);
                                    $("#ui_corp_tg").treegrid("reload");
                                } else {
                                    $('#ui_corp_edit_btn').linkbutton('enable');
                                    $.show_warning("提示", dataJson.msg);
                                }
                            }
                        });
                    }
                }],
                onLoad: function () {
                    $("#id").val(row.id);
                    $("#Name").val(row.text);
                    $('#Sort').numberspinner('setValue', row.Sort);
                },
                onClose: function () {
                    $("#ui_corp_edit_dialog").dialog('destroy');
                }
            });
        }

        //删除公司
        function corporation_delete() {
            var row = $("#ui_corp_tg").datagrid("getSelected");
            if (!row) {
                $.show_warning("提示", "请先勾选要删除的公司");
                return;
            }
            $.messager.confirm('提示', '确定删除：' + row.text + '？如果有子公司也会同时删除！', function (r) {
                if (r) {
                    corpIds = "";
                    recursionGetIds(row);
                    $.ajax({
                        url: '@Url.Action("Delete", "Corporation")',
                        data: { "deleteCorpIds": corpIds + row.id },
                        type: "POST",
                        dataType: "JSON",
                        success: function (data) {
                            if (data.success) {
                                $.show_warning("提示", data.msg);
                                $("#ui_corp_tg").treegrid("reload");
                                if ($('#tabs').tabs('exists', '部门管理')) {
                                    $('#tabs').tabs('getTab', '部门管理').panel('refresh');
                                }
                                $("#ui_corp_layout").layout("collapse", "east");
                            } else {
                                $.show_warning("提示", data.msg);
                            }
                        }
                    });
                }
            });
        }

    </script>

</body>
</html>