DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Controllers/ButtonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using Tracy.Frameworks.Common.Extends;
using Tracy.WebFrameworks.IService;

namespace Tracy.WebFrameworks.Offline.Site.Controllers
{
    public class ButtonController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// 获取当前用户当前页面可访问的按钮
        /// </summary>
        /// <param name="menuCode"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetButtonByUserIdAndMenuCode(string menuCode, string pageName)
        {
            if (menuCode.IsNullOrEmpty())
            {
                throw new ArgumentNullException("menuCode");
            }

            var result = string.Empty;
            using (var factory = new ChannelFactory<IWebFxsButtonService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.GetButtonByUserIdAndMenuCode(menuCode, pageName, CurrentUserInfo.Id);
                if (rs.ReturnCode == Entity.ReturnCodeType.Success)
                {
                    result = rs.Content;
                }
            }

            return Content(result);
        }

    }
}

DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Tracy.WebFrameworks.Entity;
using Tracy.WebFrameworks.Entity.ViewModel;
using Tracy.WebFrameworks.IService;
using Tracy.Frameworks.Common.Extends;
using Tracy.WebFrameworks.Entity.Enum;

namespace Tracy.WebFrameworks.Offline.Site.Controllers
{
    /// <summary>
    /// 通用
    /// </summary>
    public class CommonController : BaseController
    {
        /// <summary>
        /// 获取组织机构树数据
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult GetOrgTreeData(GetOrgTreeDataRQ request)
        {
            var result = string.Empty;
            StringBuilder sb = new StringBuilder();

            using (var factory = new ChannelFactory<IWebFxsCommonService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.GetOrgTreeData();
                if (rs.ReturnCode == ReturnCodeType.Success)
                {
                    var corps = rs.Content;
                    if (corps.HasValue())
                    {
                        var orgTreeType = request.OrgType.ToEnum<OrgTreeType>();
                        if (orgTreeType == OrgTreeType.Corporation)//按公司
                        {
                            sb.Append(RecursionCorp(corps, 0));
                            sb = sb.Remove(sb.Length - 2, 2);
                            result = sb.ToString();
                        }
                        if (orgTreeType == OrgTreeType.Department)//按部门
                        {
                            sb.Append(RecursionCorpDepartment(corps, 0));
                            sb = sb.Remove(sb.Length - 2, 2);
                            result = sb.ToString();
                        }
                    }
                    else
                    {
                        result = "[]";
                    }
                }
            }

            return Content(result);
        }

        #region Private method

        /// <summary>
        /// 递归所有公司和部门(无限层级)
        /// </summary>
        /// <param name="list"></param>
        /// <param name="parentId"></param>
        /// <returns></returns>
        private string RecursionCorpDepartment(List<Corporation> list, int parentId)
        {
            //TODO:还有个bug，非最底部的节点下如果有部门展示不出来
            StringBuilder sb = new StringBuilder();
            var childCorps = list.Where(p => p.ParentId == parentId).ToList();
            if (childCorps.HasValue())
            {
                sb.Append("[");
                for (int i = 0; i < childCorps.Count; i++)
                {
                    var childStr = RecursionCorpDepartment(list, childCorps[i].Id);
                    if (!childStr.IsNullOrEmpty())
                    {
                        sb.Append("{\"id\":\"" + childCorps[i].Id.ToString() + "\",\"ParentId\":\"" + childCorps[i].ParentId.ToString() + "\",\"text\":\"" + childCorps[i].Name + "\",\"children\":");
                        sb.Append(childStr);
                    }
                    else
                    {
                        //公司下是否有部门
                        var departments = childCorps[i].Department.ToList();
                        if (departments.HasValue())
                        {
                            var departmentStr = RecursionDepartment(departments, 0);
                            sb.Append("{\"id\":\"" + childCorps[i].Id.ToString() + "\",\"ParentId\":\"" + childCorps[i].ParentId.ToString() + "\",\"text\":\"" + childCorps[i].Name + "\",\"children\":");
                            sb.Append(departmentStr);
                        }
                        else
                        {
                            sb.Append("{\"id\":\"" + childCorps[i].Id.ToString() + "\",\"ParentId\":\"" + childCorps[i].ParentId.ToString() + "\",\"text\":\"" + childCorps[i].Name + "\"},");
                        }
                    }

                }
                sb.Remove(sb.Length - 1, 1);
                sb.Append("]},");
            }
            return sb.ToString();
        }

        /// <summary>
        /// 递归所有部门
        /// </summary>
        /// <param name="list"></param>
        /// <param name="parentId"></param>
        /// <returns></returns>
        private string RecursionDepartment(List<Department> list, int parentId)
        {
            StringBuilder sb = new StringBuilder();
            var childDepts = list.Where(p => p.ParentId == parentId).ToList();
            if (childDepts.HasValue())
            {
                sb.Append("[");
                for (int i = 0; i < childDepts.Count; i++)
                {
                    var childStr = RecursionDepartment(list, childDepts[i].Id);
                    if (!childStr.IsNullOrEmpty())
                    {
                        sb.Append("{\"id\":\"" + childDepts[i].Id.ToString() + "\",\"ParentId\":\"" + childDepts[i].ParentId.ToString() + "\",\"text\":\"" + childDepts[i].Name + "\",\"children\":");
                        sb.Append(childStr);
                    }
                    else
                    {
                        sb.Append("{\"id\":\"" + childDepts[i].Id.ToString() + "\",\"ParentId\":\"" + childDepts[i].ParentId.ToString() + "\",\"text\":\"" + childDepts[i].Name + "\"},");
                    }

                }
                sb.Remove(sb.Length - 1, 1);
                sb.Append("]},");
            }
            return sb.ToString();
        }

        /// <summary>
        /// 递归所有公司
        /// </summary>
        /// <param name="list"></param>
        /// <param name="parentId"></param>
        /// <returns></returns>
        private string RecursionCorp(List<Corporation> list, int parentId)
        {
            StringBuilder sb = new StringBuilder();
            var childCorps = list.Where(p => p.ParentId == parentId).ToList();
            if (childCorps.HasValue())
            {
                sb.Append("[");
                for (int i = 0; i < childCorps.Count; i++)
                {
                    var childStr = RecursionCorp(list, childCorps[i].Id);
                    if (!childStr.IsNullOrEmpty())
                    {
                        sb.Append("{\"id\":\"" + childCorps[i].Id.ToString() + "\",\"ParentId\":\"" + childCorps[i].ParentId.ToString() + "\",\"text\":\"" + childCorps[i].Name + "\",\"children\":");
                        sb.Append(childStr);
                    }
                    else
                    {
                        sb.Append("{\"id\":\"" + childCorps[i].Id.ToString() + "\",\"ParentId\":\"" + childCorps[i].ParentId.ToString() + "\",\"text\":\"" + childCorps[i].Name + "\"},");
                    }

                }
                sb.Remove(sb.Length - 1, 1);
                sb.Append("]},");
            }
            return sb.ToString();
        }

        #endregion

    }
}

DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using Tracy.WebFrameworks.Entity;
using Tracy.WebFrameworks.Entity.ViewModel;
using Tracy.WebFrameworks.IService;
using Tracy.Frameworks.Common.Extends;
using System.Text;
using Tracy.Frameworks.Common.Const;
using Tracy.WebFrameworks.Entity.Enum;
using Tracy.WebFrameworks.Offline.Site.Filters;

namespace Tracy.WebFrameworks.Offline.Site.Controllers
{
    /// <summary>
    /// 部门管理
    /// </summary>
    public class DepartmentController : BaseController
    {
        [LoginAuthorization]
        public ActionResult Index()
        {
            return View();
        }

        [LoginAuthorization]
        public ActionResult Add()
        {
            return View();
        }

        /// <summary>
        /// 添加部门
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Add(AddDepartmentRQ request)
        {
            var flag = false;
            var msg = string.Empty;

            using (var factory = new ChannelFactory<IWebFxsDepartmentService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.AddDepartment(request, base.CurrentUserInfo);
                if (rs.ReturnCode == ReturnCodeType.Success && rs.Content == true)
                {
                    flag = true;
                    msg = "添加成功!";
                }
                else
                {
                    msg = "添加失败!";
                }
            }

            return Json(new { success = flag, msg = msg }, JsonRequestBehavior.AllowGet);
        }

        [LoginAuthorization]
        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(EditDepartmentRQ request)
        {
            var flag = false;
            var msg = string.Empty;

            using (var factory = new ChannelFactory<IWebFxsDepartmentService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.EditDepartment(request, base.CurrentUserInfo);
                if (rs.ReturnCode == ReturnCodeType.Success && rs.Content == true)
                {
                    flag = true;
                    msg = "修改成功!";
                }
                else
                {
                    msg = "修改失败!";
                }
            }

            return Json(new { success = flag, msg = msg }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete(DeleteDepartmentRQ request)
        {
            var flag = false;
            var msg = string.Empty;

            using (var factory = new ChannelFactory<IWebFxsDepartmentService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.DeleteDepartment(request);
                if (rs.ReturnCode == ReturnCodeType.Success && rs.Content == true)
                {
                    flag = true;
                    msg = "删除成功!";
                }
                else
                {
                    msg = "删除失败!";
                }
            }

            return Json(new { success = flag, msg = msg }, JsonRequestBehavior.AllowGet);
        }



        /// <summary>
        /// 获取指定公司下的部门
        /// 如果没有指定则获取所有公司下的所有部门
        /// </summary>
        /// <returns></returns>
        public ActionResult GetDepartmentByCorp(GetDepartmentByCorpRQ request)
        {
            var result = string.Empty;
            StringBuilder sb = new StringBuilder();
            using (var factory = new ChannelFactory<IWebFxsDepartmentService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.GetDepartmentByCorp(request);
                if (rs.ReturnCode == Entity.ReturnCodeType.Success)
                {
                    var depts = rs.Content;
                    if (depts.HasValue())
                    {
                        sb.Append(RecursionDepartment(depts, 0));
                        sb = sb.Remove(sb.Length - 2, 2);
                        result = sb.ToString();
                    }
                    else
                    {
                        result = "[]";
                    }
                }
            }

            return Content(result);
        }

        /// <summary>
        /// 获取部门下的所有用户
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public ActionResult GetUserByDepartment(GetUserByDepartmentRQ request, int page, int rows)
        {
            var result = string.Empty;
            if (request == null)
            {
                request = new GetUserByDepartmentRQ();
            }
            request.PageIndex = page;
            request.PageSize = rows;
            using (var factory = new ChannelFactory<IWebFxsDepartmentService>("*"))
            {
                var client = factory.CreateChannel();
                var rs = client.GetUserByDepartment(request);
                if (rs.ReturnCode == ReturnCodeType.Success)
                {
                    result = "{\"total\": " + rs.Content.TotalCount + ",\"rows\":" + rs.Content.Entities.ToJson(dateTimeFormat: DateFormat.DATETIME) + "}";
                }
            }

            return Content(result);
        }

        #region Private method
        private string RecursionDepartment(List<Department> list, int parentId)
        {
            StringBuilder sb = new StringBuilder();
            var childDepts = list.Where(p => p.ParentId == parentId).ToList();
            if (childDepts.HasValue())
            {
                sb.Append("[");
                for (int i = 0; i < childDepts.Count; i++)
                {
                    var childStr = RecursionDepartment(list, childDepts[i].Id);
                    if (!childStr.IsNullOrEmpty())
                    {
                        sb.Append("{\"id\":\"" + childDepts[i].Id.ToString() + "\",\"ParentId\":\"" + childDepts[i].ParentId.ToString() + "\",\"Code\":\"" + childDepts[i].Code + "\",\"CorpName\":\"" + childDepts[i].CorporationName + "\",\"Enabled\":\"" + childDepts[i].Enabled.Value + "\",\"Sort\":\"" + childDepts[i].Sort.Value.ToString() + "\",\"CreatedTime\":\"" + childDepts[i].CreatedTime.Value.ToString(DateFormat.DATETIME) + "\",\"text\":\"" + childDepts[i].Name + "\",\"children\":");
                        sb.Append(childStr);
                    }
                    else
                    {
                        //sb.Append("{\"id\":\"" + childDepts[i].Id.ToString() + "\",\"ParentId\":\"" + childDepts[i].ParentId.ToString() + "\",\"Code\":\"" + childDepts[i].Code + "\",\"CorpName\":\"" + childDepts[i].CorporationName + "\",\"Enabled\":\"" + childDepts[i].Enabled.Value + "\",\"Sort\":\"" + childDepts[i].Sort.Value.ToString() + "\",\"CreatedTime\":\"" + childDepts[i].CreatedTime.Value.ToString(DateFormat.DATETIME) + "\",\"attributes\":{\"ParentId\":\"" + childDepts[i].ParentId.ToString() + "\"}\",\"text\":\"" + childDepts[i].Name + "\"},");
                        sb.Append("{\"id\":\"" + childDepts[i].Id.ToString() + "\",\"ParentId\":\"" + childDepts[i].ParentId.ToString() + "\",\"Code\":\"" + childDepts[i].Code + "\",\"CorpName\":\"" + childDepts[i].CorporationName + "\",\"Enabled\":\"" + childDepts[i].Enabled.Value + "\",\"Sort\":\"" + childDepts[i].Sort.Value.ToString() + "\",\"CreatedTime\":\"" + childDepts[i].CreatedTime.Value.ToString(DateFormat.DATETIME) + "\",\"text\":\"" + childDepts[i].Name + "\"},");
                    }

                }
                sb.Remove(sb.Length - 1, 1);
                sb.Append("]},");
            }
            return sb.ToString();
        }

        #endregion

    }
}

DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Views/Department/Add.cshtml
<div style="padding: 15px; overflow: hidden">
    <form id="ui_department_addform" method="post" action="">
        <table class="tableForm" width="100%">
            <tr>
                <th>
                    名称：
                </th>
                <td>
                    <input type="text" name="Name" id="Name"
                           class="easyui-validatebox" data-options="required:true" autocomplete="off" />
                </td>
            </tr>
            <tr>
                <th>
                    编码：
                </th>
                <td>
                    <input type="text" name="Code" id="Code"
                           class="easyui-validatebox" data-options="required:true" autocomplete="off" />
                </td>
            </tr>
            <tr>
                <th>
                    排序：
                </th>
                <td>
                    <input name="Sort" class="easyui-numberspinner" style="width: 70px;"
                           value="10" data-options="min:1,max:100,editable:false">
                </td>
            </tr>
            <tr>
                <th>
                    父节点：
                </th>
                <td>
                    @*<input class="easyui-combotree" id="comboParent" name="comboParent"
                           data-options="url: '@Url.Action("GetOrgTreeData", "Common")'+'?orgType=2',lines:true" />*@
                    <input id="comboParent" />
                    <img style="cursor: pointer; vertical-align: middle;" onclick="$('#comboParent').combotree('clear');"
                         alt="清空父节点" title="清空父节点" src='@Url.Content("~/Content/easyui/icon/edit-clear.png")' />
                </td>
            </tr>
        </table>
    </form>
</div>

DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Views/Department/Edit.cshtml
<div style="padding: 15px; overflow: hidden">
    <form id="ui_dept_editform" method="post" action="">
        <table class="tableForm" width="100%">
            <tr>
                <th>
                    名称：
                </th>
                <td>
                    <input type="hidden" name="id" id="id" />
                    <input type="text" name="Name" id="Name"
                           class="easyui-validatebox" data-options="required:true" autocomplete="off" />
                </td>
            </tr>
            <tr>
                <th>
                    排序：
                </th>
                <td>
                    <input id="Sort" name="Sort" class="easyui-numberspinner"
                           style="width: 70px;" data-options="min:1,max:100,editable:false">
                </td>
            </tr>
        </table>
    </form>
</div>

DEV/Tracy.WebFrameworks/Tracy.WebFrameworks.Offline.Site/Views/Department/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link type="image/x-icon" rel="shortcut icon" href="~/Content/images/favicon.ico" />
    @Styles.Render("~/Content/easyui/bootstrap")
    @Styles.Render("~/Content/site")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/easyui")
    @Scripts.Render("~/bundles/common")
    <title>部门管理</title>
</head>
<body>
    <div id="ui_dept_layout" class="easyui-layout" data-options="fit:true,border:false">
        <div data-options="region:'west',split:true,title:'组织机构'" style="width: 180px; padding: 10px;">
            <div>
                <ul id="treeOrg"></ul>
            </div>
        </div>
        <div data-options="region:'center',border:false, title:'部门列表'">
            <table id="ui_dept_tg" data-options="fit:true,border:false"></table>
        </div>
        <input type="hidden" id="hidCorpId" value="0" />
    </div>
    @if (false)
    {
        <script type="text/javascript" src="~/Scripts/jquery-1.8.2.js"></script>
    }

    <script type="text/javascript">
        $(function () {
            //默认加载组织机构和所有公司的部门列表
            $('#treeOrg').tree({
                method: 'GET',
                url: '@Url.Action("GetOrgTreeData", "Common")' + "?orgType=1",
                lines: true,
                onClick: function (node) {
                    var centerPanel = $("#ui_dept_layout").layout("panel", "center");
                    centerPanel.panel("setTitle", "部门列表 - " + node.text);
                    $("#hidCorpId").val(node.id);

                    loadDepartments(node.id);
                }
            });

            //默认加载所有公司下的所有部门
            loadDepartments(0);
        });

        //加载指定公司下的所有部门
        function loadDepartments(corpId) {
            $.ajax({
                url: '@Url.Action("GetButtonByUserIdAndMenuCode", "Button")',
                type: "POST",
                dataType: "json",
                data: { "menuCode": "depart", "pageName": "department" },
                timeout: 5000,
                success: function (data) {
                    if (data.success) {
                        var oldSelectDeptId;
                        var toolbar = getToolBar(data);
                        if (data.browser) {
                            $("#ui_dept_tg").treegrid({
                                url: '@Url.Action("GetDepartmentByCorp", "Department")' + "?corporationId=" + corpId,
                                idField: 'id',
                                treeField: 'text',
                                rownumbers: true,
                                columns: [[
                                            { field: 'text', title: '部门名称', width: 150 },
                                            { field: 'Code', title: '编码', width: 80 },
                                            { field: 'CorpName', title: '所属公司', width: 150 },
                                            {
                                                field: 'Enabled', title: '启用', sortable: true, width: 60, align: 'center',
                                                formatter: function (value, row, index) {
                                                    return value ? '<img src="@Url.Content("~/Content/easyui/icon/chk_checked.gif")" alt="已启用" title="公司已启用" />' : '<img src="@Url.Content("~/Content/easyui/icon/chk_unchecked.gif")" alt="未启用" title="公司未启用" />';
                                                }
                                            },
                                            { field: 'Sort', title: '排序', width: 60 },
                                            { field: 'CreatedTime', title: '创建时间', width: 150 }
                                ]],
                                toolbar: toolbar.length == 0 ? null : toolbar
                            });
                        }
                        else {
                            $.show_warning("提示", "无权限，请联系管理员！");
                        }
                    } else {
                        $.show_warning("错误", data.result);
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    if (textStatus == "timeout") {
                        $.show_warning("提示", "请求超时，请刷新当前页重试！");
                    }
                    else {
                        $.show_warning("错误", textStatus + "：" + errorThrown);
                    }
                }
            })
        };

        var deptIds = "";
        function recursionGetIds(rows) {
            if (rows.children != undefined) {
                $.each(rows.children, function (i, row) {
                    deptIds += row.id + ",";
                    recursionGetIds(row);
                });
            }
        }

        //添加部门
        //必须先选择左边的公司然后才可以添加
        function department_add() {
            var nodeCorp = $('#treeOrg').tree('getSelected');
            if (!nodeCorp) {
                $.show_warning("提示", "请先选择左边的公司然后再添加!");
                return false;
            }

            $("<div/>").dialog({
                id: "ui_department_add_dialog",
                href: '@Url.Action("Add", "Department")',
                title: "添加部门",
                height: 350,
                width: 460,
                modal: true,
                buttons: [{
                    id: "ui_department_add_btn",
                    text: '添 加',
                    handler: function () {
                        $("#ui_department_addform").form("submit", {
                            url: '@Url.Action("Add", "Department")',
                            onSubmit: function (param) {
                                $('#ui_department_add_btn').linkbutton('disable');
                                if ($(this).form('validate')) {
                                    var t = $("#comboParent").combotree('tree');
                                    var node = t.tree('getSelected');
                                    param.CorpId = $("#hidCorpId").val();
                                    param.ParentId = node.id;
                                    return true;
                                }
                                else {
                                    $('#ui_department_add_btn').linkbutton('enable');
                                    return false;
                                }
                            },
                            success: function (data) {
                                var dataJson = eval('(' + data + ')');
                                if (dataJson.success) {
                                    $("#ui_department_add_dialog").dialog('destroy');
                                    $.show_warning("提示", dataJson.msg);
                                    $("#ui_dept_tg").treegrid("reload");
                                } else {
                                    $('#ui_department_add_btn').linkbutton('enable');
                                    $.show_warning("提示", dataJson.msg);
                                }
                            }
                        });
                    }
                }],
                onLoad: function () {
                    $("#Name").focus();

                    var hidCorpId = $("#hidCorpId").val();
                    $("#comboParent").combotree({
                        url: '@Url.Action("GetDepartmentByCorp", "Department")' + "?corporationId=" + hidCorpId,
                        lines: true
                    });
                },
                onClose: function () {
                    $("#ui_department_add_dialog").dialog('destroy');
                }
            });
        };

        //修改部门
        function department_edit() {
            var row = $("#ui_dept_tg").treegrid("getSelected");
            if (!row) {
                $.show_warning("提示", "请先选择要修改的部门");
                return;
            }
            $("<div/>").dialog({
                id: "ui_dept_edit_dialog",
                href: '@Url.Action("Edit", "Department")',
                title: "修改部门",
                height: 350,
                width: 460,
                modal: true,
                buttons: [{
                    id: "ui_dept_edit_btn",
                    text: '修 改',
                    handler: function () {
                        $("#ui_dept_editform").form("submit", {
                            url: '@Url.Action("Edit", "Department")',
                            onSubmit: function (param) {
                                $('#ui_dept_edit_btn').linkbutton('disable');
                                if ($(this).form('validate'))
                                    return true;
                                else {
                                    $('#ui_dept_edit_btn').linkbutton('enable');
                                    return false;
                                }
                            },
                            success: function (data) {
                                var dataJson = eval('(' + data + ')');
                                if (dataJson.success) {
                                    $("#ui_dept_edit_dialog").dialog('destroy');
                                    $.show_warning("提示", dataJson.msg);
                                    $("#ui_dept_tg").treegrid("reload");
                                } else {
                                    $('#ui_dept_edit_btn').linkbutton('enable');
                                    $.show_warning("提示", dataJson.msg);
                                }
                            }
                        });
                    }
                }],
                onLoad: function () {
                    $("#id").val(row.id);
                    $("#Name").val(row.text);
                    $('#Sort').numberspinner('setValue', row.Sort);
                },
                onClose: function () {
                    $("#ui_dept_edit_dialog").dialog('destroy');
                }
            });
        }

        //删除部门
        function department_delete() {
            var row = $("#ui_dept_tg").datagrid("getSelected");
            if (!row) {
                $.show_warning("提示", "请先勾选要删除的部门");
                return;
            }
            $.messager.confirm('提示', '确定删除：' + row.text + '？如果有子部门也会同时删除！', function (r) {
                if (r) {
                    deptIds = "";
                    recursionGetIds(row);
                    $.ajax({
                        url: '@Url.Action("Delete", "Department")',
                        data: { "deleteDeptIds": deptIds + row.id },
                        type: "POST",
                        dataType: "JSON",
                        success: function (data) {
                            if (data.success) {
                                $.show_warning("提示", data.msg);
                                $("#ui_dept_tg").treegrid("reload");
                                if ($('#tabs').tabs('exists', '部门管理')) {
                                    $('#tabs').tabs('getTab', '部门管理').panel('refresh');
                                }
                                //$("#ui_dept_layout").layout("collapse", "east");
                            } else {
                                $.show_warning("提示", data.msg);
                            }
                        }
                    });
                }
            });
        };

        //全部展开
        function department_expandall() {
            $("#ui_dept_tg").treegrid("expandAll");
        };

        //全部折叠
        function department_collapseall() {
            $("#ui_dept_tg").treegrid("collapseAll");
        };

    </script>

</body>
</html>